/**
 * All built-in operations. Importing this module registers them with the
 * node registry as a side effect.
 */
import './io/text-input'
import './io/number-input'
import './io/file-input'
import './io/download'
import './io/preview'
import './encoding/base64'
import './encoding/base32'
import './encoding/base58'
import './encoding/hex'
import './encoding/url'
import './encoding/html-entities'
import './encoding/binary'
import './text/case'
import './text/find-replace'
import './text/regex'
import './text/trim'
import './text/split-join'
import './logic/xor'
import './logic/misc'
import './data/json'
import './data/bytes'
import './flow/list'
import './flow/hof'
import './math/arith'
import './math/compare'
import './hashing/sha'
import './hashing/md5'
import './hashing/hmac'
